### ISSUE TITLE
MariaDB4j

### ISSUE THREAD

**Issue by vorburger** [vincent-fuchs/in-memory-testing#1]
@vincent-fuchs instead of using H2 here, you may be interested in (my) https://github.com/vorburger/MariaDB4j?

Just a thought / suggestion - please do ignore and/or close this issue if N/A.

**Comment by vincent-fuchs** [comment]
thanks @vorburger for the suggestion - but this is a very old repo I had created for a presentation / training I was giving few years back, I don't really maintain it
